# -*- coding: utf-8 -*-
"""task_2.14

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pdTjqQbqNrGF0He_dtaF1fuExSi5X7uM
"""

parts = ['Is','Chicago','Not','Chicago!']
print(''.join(parts))
print(','.join(parts))
print(''.join(parts))
a = 'Is Chicago'
b = 'Not chickago'
print(a + ' ' + b)
'{} {}.format(a,b)'
print(a + '' +b)
data = ['ACME',58,91.2]
print(','.join(str(d) for d in data))
f = open('file.txt','w+')
chunk1 = 'Hello, '
chunk2 = 'world!'
print(f.write(chunk1+chunk2))
def sample():
  yield 'Is'
  yield 'Chicago'  
  yield 'Not'
  yield 'Chicago?'
text = ''.join(sample()) 
print(text) 
for part in sample(): 
  f.write(part)

